
services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env #only for local development
    environment:
      - PYTHONUNBUFFERED=1
    image: agent-process:latest
